### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by HoNKoT** [HoNKoT/javaFoundationsExercise#1]
Here is Error Log.
>Exception in thread "main" java.lang.SecurityException: Prohibited package name: java.foundation.example
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)

**Comment by HoNKoT** [comment]
According to this website, Java does not allow to use "java" package as user's own one.
http://stackoverflow.com/questions/3804442/why-java-lang-securityexception-prohibited-package-name-java-is-required
